services.coordinator.web.auth.type: "keycloak"

services.keycloak {
  issuer-url: "http://keycloak:8080/realms/iceberg"
  client-id: "dremio-web"
  client-secret: "dremio-secret"
  redirect-uri: "http://localhost:9047/api/v3/oidc/callback"
  role.sync-mode: "additive"
}
